# Bluetube. Profiles.
# TOML. https://pypi.org/project/toml/


# Default profile.
# Use it as an example for new profiles as well.
[_default]

    [_default.bluetooth]
    # enter your device ID in the line below
    # deviceID="YOUR_RECEIVER_DEVICE_ID"

    [_default.audio]
    # Specify audio format: "best", "aac", "flac", "mp3", "m4a",
    #                       "opus", "vorbis", or "wav"; "best" by default;
    output_format = "mp3"

    [_default.video]
    # configure audio and video codecs like in the command line below
    # working example:
    #    codecs_options=-vcodec h263 -acodec aac -s 352x288
    # codecs_options="OPTIONS"

    # set a video format e.g 3gp. Required!
    output_format = "3gp"

# save downloaded and converted video here:
# local = "PATH"