# Bluetube. Profiles.
# TOML. https://pypi.org/project/toml/


# The download options.
# Other profile inherits these options.
[__download__]

    [__download__.audio]
    # Specify audio format: "best", "aac", "flac", "mp3", "m4a",
    #                       "opus", "vorbis", or "wav"; "best" by default;
    output_format = "mp3"

    [__download__.video]
    # Download the video in this format. The source might not allow it!
    # If this option is empty, download it in the best quality.
    # Currently supported by the downloader: mp4|flv|ogg|webm|mkv|avi.
    # For more information see:
    #   https://github.com/ytdl-org/youtube-dl/blob/master/README.md#format-selection
    output_format = ""


# Default profile.
# Use it as an example for new profiles as well.
[profile_1]

    [profile_1.convert]
    # Convert to this format.
    # output_format = "3gp"

    # other ffmpeg option can be set here.
    # For more info see "ffmpeg --help"
    # codecs_options = "-vcodec h263 -acodec aac -s 352x288"

    [profile_1.send]
    # Enter your pair bluetooth device ID here.
    # bluetooth_device_id = "YOUR_RECEIVER_DEVICE_ID"

    # Save downloaded and/or converted video here:
    # local_path = "~/Downloads"
