# Bluetube. Profiles.
# TOML. https://pypi.org/project/toml/


# The download options.
# Other profiles inherit these options. DON'T REMOVE THIS SECTION.
[__download__]

    [__download__.audio]
    # Specify audio format: "best", "aac", "flac", "mp3", "m4a",
    #                       "opus", "vorbis", or "wav"; "best" by default;
    # For more information see:
    #   https://github.com/ytdl-org/youtube-dl/blob/master/README.md#format-selection
    output_format = "mp3"

    [__download__.video]
    # Download the video in this format. The source might not allow it!
    # If this option is empty, download it in the best quality.
    # Currently supported by the downloader: mp4|flv|ogg|webm|mkv|avi.
    # For more information see:
    #   https://github.com/ytdl-org/youtube-dl/blob/master/README.md#format-selection
    output_format = ""


# Default profile.
# Edit it and use as an example for new profiles as well.
[default]

    [default.convert]
    # Convert to this format.
    output_format = "mp4"

    # Other ffmpeg option can be set here.
    # For more info see "ffmpeg --help"
    # codecs_options = "-vcodec h263 -acodec aac -s 352x288"

    [default.send]
    # Enter your pair bluetooth device ID here.
    # bluetooth_device_id = "00:00:00:00:00:00"

    # Save downloaded and/or converted video here:
    local_path = "~/Downloads"
