name: a workflow POC

on:
  push:
    branches:
      - master
jobs:
  the_first_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
